services:
  mysql:
    image: mysql:8.0
    container_name: order-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql-data:/var/lib/mysql

  # ===== 新增：Redis 服务 =====
  redis:
    image: redis:7-alpine          # alpine 是小体积镜像，省空间
    container_name: order-redis
    ports:
      - "6379:6379"                 # 6379 是 Redis 默认端口，对应下面 application.yml
    volumes:
      - redis-data:/data            # 把数据存到宿主机，重启不丢

  # ===== 新增：RocketMQ 三件套（namesrv + broker + dashboard）=====
  namesrv:
    image: apache/rocketmq:5.3.3
    container_name: rmq-namesrv
    ports:
      - "9876:9876"                 # NameServer 端口，Spring Boot 里 rocketmq.name-server 连这里
    command: sh mqnamesrv
    networks:
      - rmq-net

  broker:
    image: apache/rocketmq:5.3.3
    container_name: rmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"               # Broker remoting 端口，客户端实际收发消息走这里
      - "10912:10912"
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    volumes:
      - ./broker.conf:/home/rocketmq/conf/broker.conf:ro
    depends_on:
      - namesrv
    networks:
      - rmq-net

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmq-dashboard
    ports:
      - "8082:8080"                 # 浏览器访问 http://localhost:8082（8081 让给 Proxy）
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    depends_on:
      - namesrv
    networks:
      - rmq-net


networks:
  rmq-net:

volumes:
  mysql-data:
  redis-data:
